### ISSUE TITLE
Menu Items with permissions ? 

### ISSUE THREAD

**Issue by gidaban** [Codexshaper/laravel-menu-builder#2]
Hello,

Nice job, however i have question. is possible to add menu items for specific permissions ? 

Like admin and root?

**Comment by Codexshaper** [comment]
Hello Gidaban,

Thanks for your message. We are working on routes, controller and model. We hope you can set your routes and controllers ASAP. At this moment you can set permission for menus and menuItems via middleware like

```
Route::group(['prefix' => config('menu.prefix'), 'middleware' => ['auth']], function () {
    MenuBuilder::routes();
});
```

If you are using our permission package(https://github.com/Codexshaper/laravel-permission) then you can set roles also like 

```
Route::group(['middleware' => ['role:admin']], function () {
   Route::get('admin/menu', 'AdminController@index');
});
```
If you have any issue with laravel-permission then create an issue in laravel permission we will try to solve your issue.
