### ISSUE TITLE
Is Possible to edit display template ?

### ISSUE THREAD

**Issue by gidaban** [Codexshaper/laravel-menu-builder#3]
Hello :)

AS in subject.

Is possible to edit template for display menus ?

**Comment by maab16** [comment]
Hi,
Do you mean redesign menu template? Can you send snippets or screenshots? 
Thanks

**Comment by Codexshaper** [comment]
Closed due to inactivity.

**Comment by wajihmej** [comment]
hello , well i think he mean when he need to change name in the Vuejs file nothing change in the display ! i got the same issue ! Thanks
