### ISSUE TITLE
Invalid route action in demo page

### ISSUE THREAD

**Issue by celyes** [Codexshaper/laravel-menu-builder#6]
I'm opening this issue not as an issue in the code, but rather in the demo.

**the problem:** Invalid route action: [App\Http\Controllers\sdf]. 

![image](https://user-images.githubusercontent.com/21331907/73836725-355a2c00-4810-11ea-85ca-d3227b132c75.png)

**Comment by Codexshaper** [comment]
@celyes,
Thanks for your notice. Someone put wrong route name and controller.
Demo doesn't have any controller like sdf
Secondly didn't pass method name.

Correct format is App\Http\controllerName@methodName

**Comment by celyes** [comment]
@Codexshaper thank you for your response.
looks like the issue has been solved. thank you again!

**Comment by Codexshaper** [comment]
@celyes you are welcome. If you like this package want to get more packages, don't forget to press the star button.
